extend schema @link(
  url: "https://specs.apollo.dev/nullability/v0.4",
  import: ["@semanticNonNull", "@semanticNonNullField", "@catch", "CatchTo", "@catchByDefault"]
)

extend schema @catchByDefault(to: THROW)

extend type Root
  @semanticNonNullField(name: "allPeople")
  @semanticNonNullField(name: "allFilms")

extend type PeopleConnection @semanticNonNullField(name: "people")

extend type Person @semanticNonNullField(name: "name")

extend type Planet @semanticNonNullField(name: "name")

extend type FilmsConnection @semanticNonNullField(name: "films")

extend type Film
  @semanticNonNullField(name: "title")
  @semanticNonNullField(name: "director")
